### ISSUE TITLE
SpellRare

### ISSUE THREAD

**Issue by Konfekt** [reedes/vim-wordy#21]
Regarding the check:
```vim
      if has('nvim')
        " Dynamically convert SpellBad words into SpellRare words under NeoVim.
        " See issue 15 for details: https://github.com/reedes/vim-wordy/pull/15
```
Now Vim also has `SpellRare` so perhaps better than a check for `nvim` would be one for the highlight-group `SpellRare`? Don't know how though. Perhaps check for the exact patch of Vim that brought it in?

**Comment by reedes** [comment]
I'm checking for a patch/version in _pencil_ for another feature, here: https://github.com/reedes/vim-pencil/blob/master/autoload/pencil.vim#L263-L270

If you can identify the ones associated with SpellRare, we can do something similar here.

**Comment by Konfekt** [comment]
Ok, I will grep for the SpellRare Patch. Apparently, ypu also know of no way to check for the existence of Highlight groups? Would be the cleaner solution.

**Comment by Konfekt** [comment]
Hello, I checked and `SpellRare` is there since `7.068`. Thus, why check for `nvim` at all? Vim has it since ten years, too, it seems?

**Comment by reedes** [comment]
Now that you mention it, I vaguely recall trying to use the SpellRare highlight during development and never achieved the desired behavior. It had been fixed in neovim -- hence the patch from the other user.

I haven't tried recent versions of vim to see if SpellRare had been fixed.

So, if you (or someone else) wants to dig into this to see if SpellRare now works, and ideally at the patch it was fixed, we can switch over to that highlight group. (I won't have a chance to dig into it anytime soon, sorry.)

**Comment by Konfekt** [comment]
Yep, I just played around with the very latest Vim, and the issue persists. Highlight is fine with SpellBad, but SpellRare does not light up.

**Comment by reedes** [comment]
Thanks for testing that. Closing until Vim gets SpellRare highlighting working correctly.
